### ISSUE TITLE
Account picker does not work

### ISSUE THREAD

**Issue by danifitz** [newrelic/nr1-network-telemetry#25]
## Description

Running the nerdpack, the account picker does not work. I am attaching a short video showing this behaviour: https://imgur.com/a/3yNZbVE

## Steps to Reproduce

Use `nr1 nerdpack:serve` to run the nerdpack. We do not have  nri-network-telemetry deployed - is this the problem?

## Expected Behaviour

A list of accounts would be displayed in the dropdown

## Relevant Logs / Console output

I see an error in the log
```
VM379:1 OPTIONS https://insights-collector.eu.newrelic.com/v1/accounts/2390478/events net::ERR_NAME_NOT_RESOLVED
(anonymous) @ VM379:1
t.<computed> @ nr-loader-spa-current.min.js:1
window.fetch @ wanda--wanda-ec-ui--app-release-710.js:142
Ku @ wanda--wanda-ec-ui--app-release-710.js:142
requestIdleCallback (async)
Yu @ wanda--wanda-ec-ui--app-release-710.js:142
nrWrapper @ nr-loader-spa-current.min.js:1
setTimeout (async)
nrWrapper @ nr-loader-spa-current.min.js:1
Gu @ wanda--wanda-ec-ui--app-release-710.js:142
s.emit @ wanda--wanda-ec-ui--app-release-710.js:113
value @ wanda--wanda-ec-ui--app-release-710.js:142
value @ wanda--wanda-ec-ui--app-release-710.js:142
(anonymous) @ wanda--wanda-ec-ui--app-release-710.js:142
nrWrapper @ nr-loader-spa-current.min.js:1
r @ nr-loader-spa-current.min.js:1
value @ wanda--wanda-ec-ui--app-release-710.js:142
(anonymous) @ wanda--wanda-ec-ui--app-release-710.js:142
value @ wanda--wanda-ec-ui--app-release-710.js:142
value @ wanda--wanda-ec-ui--app-release-710.js:142
r @ wanda--wanda-ec-ui--app-release-710.js:142
(anonymous) @ wanda--wanda-ec-ui--app-release-710.js:142
notifyListeners @ wanda--wanda-ec-ui--app-release-710.js:142
v @ wanda--wanda-ec-ui--app-release-710.js:142
(anonymous) @ wanda--wanda-ec-ui--app-release-710.js:142
confirmTransitionTo @ wanda--wanda-ec-ui--app-release-710.js:142
push @ wanda--wanda-ec-ui--app-release-710.js:142
o.handleClick @ react-router-dom.min.js:1
Fg @ react-dom.production.min.js:154
Eg @ react-dom.production.min.js:13
Hg @ react-dom.production.min.js:13
ae @ react-dom.production.min.js:15
Ig @ react-dom.production.min.js:155
Hc @ react-dom.production.min.js:15
Jc @ react-dom.production.min.js:16
gh @ react-dom.production.min.js:39
lg @ react-dom.production.min.js:148
re @ react-dom.production.min.js:23
Xb @ react-dom.production.min.js:40
ng @ react-dom.production.min.js:149
Se @ react-dom.production.min.js:40
nrWrapper @ nr-loader-spa-current.min.js:1
Show 10 more frames
/launcher/853f09ac-6b4b-4af8-9b2e-afef642d293c.network-telemetry-launcher?nerdpacks=local#launcher=eyJ0aW1lUmFuZ2UiOnsiYmVnaW5fdGltZSI6bnVsbCwiZW5kX3RpbWUiOm51bGwsImR1cmF0aW9uIjoxODAwMDAwfX0=&pane=eyJuZXJkbGV0SWQiOiI4NTNmMDlhYy02YjRiLTRhZjgtOWIyZS1hZmVmNjQyZDI5M2MubmV0d29yay10ZWxlbWV0cnktb3ZlcnZpZXcifQ==&state=IkVGNzkyRTQ0LUMxNTUtNjMwOC01MzZGLTZGRDkxOEQyQjgzRSI=:1 Uncaught (in promise) TypeError: Failed to fetch
```

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* NR1 CLI version used:
@datanerd/nr1/1.2.2 darwin-x64 node-v10.16.3
* Browser name and version:
Chrome for Mac: Version 78.0.3904.70
* Operating System and version:
Mac OS Mojave v10.14.3

**Comment by devfreddy** [comment]
There are seemingly two issues going on here:

1) An error fetching data from insights

> OPTIONS https://insights-collector.eu.newrelic.com/v1/accounts/2390478/events net::ERR_NAME_NOT_RESOLVED

I'm unable to reproduce this but I suspect it's a DNS/network-connectivity issue, perhaps even proxy related? @danifitz anything you can add here would be appreciated.

2) No Account data - likely an Account/User/Nerdpack permissions issue

As an enhancement we should add an empty state, both to the dropdown ("No Accounts found") and the main content area when the accounts query comes back as empty with something similar to the following, explaining some possibilities to the user:

```jsx
import { EmptyState } from "@newrelic/nr1-community";

if (accounts && accounts.length === 0) {
      return (
        <EmptyState
          buttonText=''
          description={
            "No accounts found for this Nerdpack or for your user. Please see your Nerdpack Manager with concerns."
          }
          heading={"No Accounts Found"}
        />
      );
    }
```

We're hoping for the release of a platform supported AccountPicker in the near-term. I'm going to put this on hold until that time and we can decide the best way to implement this.

**Comment by devfreddy** [comment]
Just experienced this, can confirm its # 2 from above - no account data. We should implement something similar to the above suggestion.

**Comment by tangollama** [comment]
@devfreddy @danielgolden is this still an issue?

**Comment by madecki** [comment]
I'll take this one
